[SERVICE]
    Flush         1
    Grace         30
    Log_Level     info

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224

[FILTER]
    Name          record_modifier
    Match         *
    Record        environment production
    Record        application ipredict

[OUTPUT]
    Name          file
    Match         *
    Path          /var/log/ipredict
    File          containers.log
    Format        out_file
